os: linux

language: shell

branches:
  only:
    - radarr-striptracks #replace variables, omit brackets

services:
  - docker

env:
  global:
    - DOCKERHUB="linuxserver/mods" #don't modify
    - BASEIMAGE="radarr" #replace
    - MODNAME="striptracks" #replace

jobs:
  include:
    - stage: PR-BuildImage
      if: (type IN (pull_request))
      script:
        # Build variables
        - VERSION=$(git describe --tags --always)
        # Build image
        - docker build --no-cache
          --build-arg VERSION=${VERSION}
          -t ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}-${TRAVIS_COMMIT} .
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build variables
        - VERSION=$(git describe --tags --always)
        # Build image
        - docker build --no-cache
          --build-arg VERSION=${VERSION}
          -t ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}-${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}-${TRAVIS_COMMIT} ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}-${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB}:${BASEIMAGE}-${MODNAME}